stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar

variables:
    APPLICATION_NAME: astarte_core

mix:test-ci:
    image: elixir:1.8.1
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
        - mix format --check-formatted
