language: elixir
dist: bionic
elixir:
  - 1.10.1
otp_release:
  - 22.2
env:
  - MIX_ENV=test
cache:
  directories:
    - deps
    - _build
before_script:
  # Needed or Elixir 1.6 will fail due to a non-updated index
  - ~/.mix/rebar3 update
script:
  - mix format --check-formatted
  - mix coveralls.travis
